### ISSUE TITLE
.and with block subject doesn't seem to call the block multiple times

### ISSUE THREAD

**Issue by bertBruynooghe** [rspec/rspec-expectations#748] opened 2015-03-07 21:32 UTC
I'm trying to combine two custom matchers using block expectations.

This is the example:

    expect{puts "test"}.to matcher1.and matcher2

And these are the matchers:

    RSpec::Matchers.define :matcher1 do |resource|
      supports_block_expectations

      match do |actual|
        puts "before matcher1"
        actual[]
        puts "after matcher1"
        true
      end
    end

    RSpec::Matchers.define :matcher2 do
      supports_block_expectations

      match do |actual|
        puts "before matcher2"
        actual[]
        puts "after matcher2"
        true
      end
    end

And the output I'm getting is:

    before matcher2
    before matcher1
    test
    after matcher1
    after matcher2

While I'm expecting:

    before matcher2
    test
    after matcher2
    before matcher1
    test
    after matcher1

(To make the case a bit more concrete, this is the example that gets me into trouble:

    expect { get :index }.to apply_collection_authorization(payment)
                              .and check_class_authorization

)

**Comment by myronmarston** [comment] 2015-03-07 22:17
The fact that the block is only called once is intentional.  Block matchers are for when you're testing _side effects_ which are often not idempotent, so we don't want to run the block twice.  Consider this expectation, for example:

``` ruby
x = y = 0
expect {
  x += 1
  y += 2
}.to change { x }.to(1).and change { y }.to(2)
```

If we ran the block twice (once for each matcher) this expectation would fail even though it should pass.  In #567 we specifically put logic in place so that the matchers are "nested" to make them work properly.  I've not ever seen or heard of a situation where you'd want the block to run once per matcher.  In your `apply_collection_authorization(payment.and check_class_authorization` case, why do you want the block to run twice?  Can you paste the definitions of those matchers, what the unexpected result is that you're getting, and what you'd expect to get instead?

**Comment by bertBruynooghe** [comment] 2015-03-08 20:45
The real scenario is as follows: I need to check if controller actions have the expected authorizations:

    expect { get :index }.to apply_collection_authorization(payment)
                          .and check_class_authorization

And my first naive implementation was as follows:

    RSpec::Matchers.define :apply_collection_authorization do |resource|
      match do |actual|
        ability_class = test_ability_class_for(class_for_controller(controller))
        allow(controller).to receive(:current_ability).and_return ability_class.new(read: {id: -1})
        actual.call
        collection_instance(controller).count == 0
      end
      supports_block_expectations
    end

    RSpec::Matchers.define :check_class_authorization do
      match do |actual|
        ability_class = test_ability_class_for(class_for_controller(controller))
        allow(controller).to receive(:current_ability).and_return ability_class.new
        begin
          actual.call
        rescue CanCan::AccessDenied
          return true
        end
        false
      end
      supports_block_expectations
    end

My main goal in using .and was trying to avoid the duplication in following lines :

        expect { get :index }.to apply_collection_authorization(payment)
        expect { get :index}.to check_class_authorization
    
Knowing what I know now, I have rewritten the matchers as:

RSpec::Matchers.define :apply_collection_authorization do |resource|
      #we don't check the happy scenario; that is assumed to be checked by the regular unit test of the controller
      match do |actual|
        resource.save!
        stored_ability = controller.current_ability
        ability_class = test_ability_class_for(class_for_controller(controller))
        allow(controller).to receive(:current_ability).and_return ability_class.new(read: {id: -1})
        actual[]
        allow(controller).to receive(:current_ability).and_return stored_ability
    
        return false unless collection_instance(controller).count == 0
        actual[]
      end
      supports_block_expectations
    end
    
    RSpec::Matchers.define :check_class_authorization do
      supports_block_expectations
      match do |actual|
        stored_ability = controller.current_ability
        ability_class = test_ability_class_for(class_for_controller(controller))
        allow(controller).to receive(:current_ability).and_return ability_class.new
        begin
          return actual[] if actual[].is_a? ActionController::TestResponse
        rescue CanCan::AccessDenied
          allow(controller).to receive(:current_ability).and_return stored_ability
          return actual[]
        end
        false
      end
    end

But besides the annoying side effect that the proc is now executed at least three times, I also have the side effect that is the first expectation is failing, the second one is also reported as failing.

**Comment by myronmarston** [comment] 2015-03-09 22:10
Thanks for posting that.  I'm trying to understand the reason the nested evaluation approach isn't working for you...is it that each of the two matchers stubs the controller to behave in different ways?

In general, matchers that mutate the behavior of the object-under-test (as these matchers do) are hard to reason about and cannot generally be composed like you are attempting to do.

> My main goal in using .and was trying to avoid the duplication in following lines :
> ```
>    expect { get :index }.to apply_collection_authorization(payment)
>    expect { get :index}.to check_class_authorization
> ```

IMO, this is merely structural duplication, not duplication of knowledge (which is what DRY is really about).  Still, if you want to avoid the duplication, you can always do something like:

``` ruby
expect_get_index = expect { get :index }
expect_get_index.to apply_collection_authorization(payment)
expect_get_index.to check_class_authorization
```

**Comment by bertBruynooghe** [comment] 2015-03-10 07:58
> On 09 Mar 2015, at 23:10, Myron Marston <notifications@github.com> wrote:
> 
> Thanks for posting that. I'm trying to understand the reason the nested evaluation approach isn't working for you...is it that each of the two matchers stubs the controller to behave in different ways?
Yes, indeed. 

> In general, matchers that mutate the behavior of the object-under-test (as these matchers do) are hard to reason about and cannot generally be composed like you are attempting to do.
I seem to have found out the hard way ;)

> 
> My main goal in using .and was trying to avoid the duplication in following lines :
> 
>    expect { get :index }.to apply_collection_authorization(payment)
>    expect { get :index}.to check_class_authorization
> 
> IMO, this is merely structural duplication, not duplication of knowledge (which is what DRY is really about). 
I agree this is not duplication of knowledge, but it greatly increases readability which is my primary concern over here. 
Moreover, the .and syntax looks so enticing that sooner or later somebody is going to try it on the matchers I have foreseen (these are part of a small internal library), and this is really not giving the expected results. I guess I’ll have to review the ideas that I put into this DSL: maybe a shared example approach would be better here, but then again, it would be rally nice to pass a block to the shared example which can be evaluated multiple times. Unfortunately, this is no longer the case since Spec 2, and there seems no nice way to do it without some visible lambda magic…

> Still, if you want to avoid the duplication, you can always do something like:
> 
> expect_get_index = expect { get :index
>  }
> expect_get_index.to apply_collection_authorization(payment)
> expect_get_index.to check_class_authorization

Yes, but leaves me with less than optimal failure logs.
I definitely like the fact that I get messages like:

Failure/Error: expect { get :index }.to apply_collection_authorization(payment)
   result still contains unauthorized resources!

as this helps you to get to the core of the failure quickly.

Regards,
Bert Bruynooghe.

**Comment by myronmarston** [comment] 2015-03-10 14:36
Regardless, how it currently behaves is by design.  I don't think there's anything actionable for us to do here so I'm going to close this.

**Closed by myronmarston** 2015-03-10 14:36 UTC
