### ISSUE TITLE
Rspec exits early

### ISSUE THREAD

**Issue by HollyM021980** [rspec/rspec-expectations#853] opened 2015-09-28 16:09 UTC
Made a serious mistake in one of my expectations where i'd intended ".and_return" but instead I'd typed ".and return".  The version w/o the underscore caused a very LARGE test suite to exit early the first time it encountered the non-underscore version (using randomization). And even worse, it exited with full success. The only indication that things were off was in the number of examples run.

Granted both are valid syntax but this makes the test suite unreliable.  Was wondering if there is a better way to handle this?  Way to validate the right number of tests are run -- w/o having to wait until the tests complete??  Way to return and show an error for the non-underscore case??  Use something else for returning in this case??

**Comment by JonRowe** [comment] 2015-09-29 00:10
Can you gist a reproducible example of this? I casually tried it but the Ruby parser actually dislikes it (complains about a "void value expression")

My understanding of this is it certainly shouldn't exit your entire suite early (how would return even do that) but I'm not really keen to prevent this sort of mistake in general (as in at a spec level) as it'd probably involve overly interfering with ruby... If we can do something to stop it exiting your suite we should however

**Comment by samphippen** [comment] 2015-12-09 15:54
@HollyM021980 Thanks for this issue! Given that we couldn't reproduce this as it was, I'm going to close this issue for now. If you can give us a reproduction case I'll happily re-open this issue and hopefully we can get it fixed!

**Closed by samphippen** 2015-12-09 15:54 UTC
