### ISSUE TITLE
Include matcher does not utilize duck typing

### ISSUE THREAD

**Issue by KevinSjoberg** [rspec/rspec-expectations#978] opened 2017-03-13 15:05 UTC
Consider the following code:

```ruby
class Foo < SimpleDelegator
end
```

Now, a test:

```ruby
RSpec.describe Foo do
  it "includes bar" do
    foo = described_class.new({bar: "baz"})
    expect(foo).to include(bar: "baz")
  end
end
```

The following code will fail when it really should not. The culprit can be found in [#comparing_hash_to_a_subset?](https://github.com/rspec/rspec-expectations/blob/master/lib/rspec/matchers/built_in/include.rb#L103-L105). It currently just checks if `actual` is a `Hash`.

If we instead check if `actual` responds to `#fetch`, `#key?` and `#keys`, we can now properly test hash-like objects as well. If we allow hash-like objects, we need to expect that hash-like objects are being passed in an expectation as well. Is `#fetch`, `#key?` and `#keys` enough of an interface?

I'd be happy to take a stab at this. Before I do, it would be nice with some feedback.

Cheers

**Comment by myronmarston** [comment] 2017-03-13 16:47
I can see how nice it would be for the matcher to treat anything hash-like like a hash, but there are a number of "is a hash?" checks outside the method you identified:

* https://github.com/rspec/rspec-expectations/blob/82ab90b513dfcd0b52064f56be4b2c6218adeded/lib/rspec/matchers/built_in/include.rb#L54
* https://github.com/rspec/rspec-expectations/blob/82ab90b513dfcd0b52064f56be4b2c6218adeded/lib/rspec/matchers/built_in/include.rb#L73
* https://github.com/rspec/rspec-expectations/blob/82ab90b513dfcd0b52064f56be4b2c6218adeded/lib/rspec/matchers/built_in/include.rb#L113

Seems like we'd have to apply duck-typing to all of them. (Although we might be able to get by only applying that to the ones that check actual values: it seems less useful to support hash-like objects passed to the matcher itself as expected values).  In addition, we do similar checks for `Array` and `String`:

https://github.com/rspec/rspec-expectations/blob/82ab90b513dfcd0b52064f56be4b2c6218adeded/lib/rspec/matchers/built_in/include.rb#L133

...and if we're going to support duck typing for hashes, we should probably support it for those, too, for consistency.

> Is `#fetch?`, `#key?` and `#keys?` enough of an interface?

Should be `fetch` (not `fetch?`) and `keys` (not `keys?`).  And it looks like we use `merge`, as well.

While this is conceptually a really good idea I do have a few concerns:

* How will this affect perf?  Doing one `respond_to?` check is one thing, but doing 4 several times as part of the match logic may have a measurable perf affect.  IMO, it would be a poor tradeoff to make this matcher measurably slower for everyone just to support this case.  I'd want to see some benchmarks before merging a PR so we understand how this affects things.
* Will this make future maintenance harder?  We are committed to SemVer, which means that if we announce in the next release that the `include` matcher supports any hash-like object (based on it supporting the 4 methods discussed above), we're committing to _always_ supporting that, at least until RSpec 4.0 (and there's no reason to think we'd drop support then: I just mention it because it would be the first opportunity to re-consider our support).  The problem is: what if we need to use additional methods from the Hash interface in the future?  Adding an additional `respond_to?` check could be problematic because a hash-like object that implements the 4 methods we currently use may not implement the new one--which means adding a new `respond_to?` check for a newly used method could be a breaking change.  Or maybe we could just document this as only working for objects that implement 100% of the Hash interface, even if we don't currently check all of it; objects that are hash-like and support only _part_ of the Hash interface would not be officially supported even though the would perhaps work for now.

Anyhow, you can see there's a lot to consider here.  At the very least, before creating a ready-to-review PR it would be good to see the benchmarks so we know what kind of affect this would have.

How important is this feature to you?

**Comment by JonRowe** [comment] 2017-03-13 22:41
We could still use the respond_to checks as a fallback after we've checked it's a hash, it'll be marginally less performant for these object but the same for actual Hash subclasses

**Comment by myronmarston** [comment] 2017-03-13 22:50
> We could use the respond_to checks as a fallback after we've checked it's a hash, it'll be marginally less performant for these object but the same for actual Hash subclasses

But anytime you use `include?` for non-hashes (e.g. `expect(array).to include(item_1, item_2)`), you'd bear the cost of all the extra checks.

**Comment by JonRowe** [comment] 2017-03-13 22:59
Pretty certain we can arrange this so the major use cases avoid the scenario where multiple checks are done, we do this elsewhere special casing the common types such as Hash, Array and String etc.

**Comment by KevinSjoberg** [comment] 2017-03-14 08:13
@myronmarston great feedback.

> [...] (Although we might be able to get by only applying that to the ones that check actual values: it seems less useful to support hash-like objects passed to the matcher itself as expected values).

I totally agree. Applying duck typing to the actual values should be enough.

> How will this affect perf? Doing one respond_to? check is one thing, but doing 4 several times as part of the match logic may have a measurable perf affect. IMO, it would be a poor tradeoff to make this matcher measurably slower for everyone just to support this case. I'd want to see some benchmarks before merging a PR so we understand how this affects things.

I wrote a naive benchmark for reference.

```ruby
require "benchmark"

n = 1_000_000

Benchmark.bm(17) do |x|
  o = Object.new
  a = o = (1..1000).to_a
  h = Hash[(1..1000).map { |n| [n, n] }]
  x.report("Object#is_a?") { n.times do o.is_a?(Hash) end }
  x.report("Object#respond_to?") { n.times do o.respond_to?(:fetch) && o.respond_to?(:key?) && o.respond_to?(:keys) end }
  puts
  x.report("Array#is_a?") { n.times do a.is_a?(Hash) end }
  x.report("Array#respond_to?") { n.times do a.respond_to?(:fetch) && a.respond_to?(:key?) && a.respond_to?(:keys) end }
  puts
  x.report("Hash#is_a?") { n.times do h.is_a?(Hash) end }
  x.report("Hash#respond_to?") { n.times do h.respond_to?(:fetch) && h.respond_to?(:key?) && h.respond_to?(:keys) end }
end
```

```
                        user     system      total        real
Object#is_a?        0.080000   0.000000   0.080000 (  0.079250)
Object#respond_to?  0.150000   0.000000   0.150000 (  0.153981)

Array#is_a?         0.080000   0.000000   0.080000 (  0.073993)
Array#respond_to?   0.150000   0.000000   0.150000 (  0.149979)

Hash#is_a?          0.080000   0.000000   0.080000 (  0.079886)
Hash#respond_to?    0.190000   0.000000   0.190000 (  0.193079)
```

Couldn't the cost of checking if the actual object is hash-like be memoized? `actual` will be the same through the expectation, right? Then we only need to perform the check once.

> Will this make future maintenance harder? We are committed to SemVer, which means that if we announce in the next release that the include matcher supports any hash-like object (based on it supporting the 4 methods discussed above), we're committing to always supporting that, at least until RSpec 4.0 (and there's no reason to think we'd drop support then: I just mention it because it would be the first opportunity to re-consider our support). The problem is: what if we need to use additional methods from the Hash interface in the future? Adding an additional respond_to? check could be problematic because a hash-like object that implements the 4 methods we currently use may not implement the new one--which means adding a new respond_to? check for a newly used method could be a breaking change. Or maybe we could just document this as only working for objects that implement 100% of the Hash interface, even if we don't currently check all of it; objects that are hash-like and support only part of the Hash interface would not be officially supported even though the would perhaps work for now.

I can see how maintenance could be affected in terms of opinion. Who decides what the interface should be for Hash, Array, String and so on. On the other hand, allow expectations to be set on arbitrary objects that implement those interfaces would be a major step forward in my opinion.

**Comment by franzliedke** [comment] 2018-01-03 14:09
Cool to see that there's already an issue for this. :sunglasses: I'd love to have this as well - for the actual values only. :+1: 

My use-case: we are using a [REST client library](https://github.com/jgraichen/restify/) which wraps API responses in `Resource` classes that mostly act as proxy for the underlying objects (arrays or hashes), but add some methods useful for hypermedia navigation. We are using this API in our request specs as well, but currently I need to unpack the resource objects in my specs before I can use the `include` matcher.

It would be awesome if I could just do this:
~~~rb
expect(response).to all include('attr' => 'value')
~~~

It seems like this issue is currently just lacking the decision whether to implement this. If this decision is made, I would happily send a PR.

**Comment by JonRowe** [comment] 2018-01-05 04:31
I think we would accept this if it only applied to duck typed implementations and not the stdlib classes.

**Comment by myronmarston** [comment] 2018-01-05 04:40
Actually, it looks like a PR has already been submitted in #1012, so we should review that.

**Comment by myronmarston** [comment] 2018-01-05 05:11
I've reviewed #1012 and it addresses this issue quite nicely.  I left a couple comments and hope to see it merged soon.

**Comment by myronmarston** [comment] 2018-01-10 20:35
Closed by #1012.

**Closed by myronmarston** 2018-01-10 20:35 UTC

**Comment by franzliedke** [comment] 2018-01-11 09:42
I know I shouldn't ask... is this scheduled for any release? Minor or patch? :see_no_evil:

**Comment by JonRowe** [comment] 2018-01-11 09:56
It'll be a minor at some point that makes sense.

**Comment by myronmarston** [comment] 2018-01-11 16:56
Our changelog lists it under "3.8 Developement", which means we plan to release it in 3.8.
