### ISSUE TITLE
have_attributes raises error for Dynamic attributes set on monogid objects

### ISSUE THREAD

**Issue by agnel** [rspec/rspec-expectations#1043] opened 2018-02-12 11:50 UTC
For example, `ctr` is a dynamic attribute set on a model, say, `DailyStat`. There is no field `ctr` defined on DailyStat then the expectation fails with a `NameError: undefined method 'ctr' for class 'DailyStat'`

Usage:
```
it '...' do
  daily_stat = DailyStat.where(...).first
  expect(daily_stat).to have_attributes('ctr' => 0.5)
end
```

Can support for dynamic attributes be added in the matcher?

**Comment by myronmarston** [comment] 2018-02-12 14:48
I have no idea how mongoid works, but in general, `have_attributes` has the following requirements:

* The object needs to indicate it responds to the attribute methods (`ctr`, in this case) by returning a truthy value from `object.respond_to?(:ctr)`.
* The object needs to return the attribute value when the attribute method is invoked via `__send__` (e.g. `object.__send__(:ctr)`)

This generally works OK for dynamic attributes if the object implements them using `method_missing` and `respond_to_missing?`.  I have no idea how Mongoid implements them, but if it doesn't implement the dynamic attributes to satisfy the contract, then the matcher isn't going to work.

What's the backtrace you get?

**Comment by jagdeepsingh** [comment] 2018-05-21 07:55
@agnel the error you see is expected as per the definition of `have_attributes` method. As mentioned by @myronmarston, `have_attributes` uses `respond_to?` to check if the object has an attribute. But in mongoid, calling `obj.respond_to?(:ctr)` returns `false` unless a value is already set.

You are fetching the record from database, so i suppose the value of dynamic field would not be set at that time and that's why when you access the attribute with a getter, it results in an error. See [here](https://docs.mongodb.com/mongoid/master/tutorials/mongoid-documents/#dynamic-fields).

So, may be you should try doing it as follows:

```ruby
it '...' do
  daily_stat = DailyStat.where(...).first
  # Set it before expectation
  daily_stat[:ctr] = 0.5
  expect(daily_stat).to have_attributes('ctr' => 0.5)
end
```

**Comment by mikegee** [comment] 2019-01-07 14:14
@agnel can you confirm that `daily_stat.respond_to?(:ctr)` is `false` and that RSpec is behaving as expected here?

**Comment by mltsy** [comment] 2019-01-25 16:49
Yeah, Mongoid doesn't define getters for dynamic attributes until you write/access them with `[]` first.  This is an interesting case where it would be nice if the matcher titled `have_attributes` worked on MongoID models, but the responsibility probably belongs in some kind of mongoID-RSpec integration gem, like... mongoid-rspec (except that seems to be for testing model declaration, not instance data, unfortunately, so I'm not sure whether a PR would be accepted there either...)

**Comment by pirj** [comment] 2019-05-08 20:27
Would you consider using `its` from [`rspec-its`](https://github.com/rspec/rspec-its) an option?
```
subject(:daily_stat) { DailyStat.where(...).first }
its([:ctr]) { is_expected.to eq(0.5) }
```

Notice square brackets.
> When the subject implements the [] operator, you can pass in an array with a single key to refer to the value returned by that operator when passed that key as an argument.

**Comment by mltsy** [comment] 2019-05-20 18:34
That's a nice work-around at least - doesn't remove the surprise of `have_attributes` not working properly with MongoID dynamic fields, but does provide an alternative - but I feel like there are several alternatives that are simple enough and the main issue is just that it takes a developer by surprise and requires some debugging, followed by a google search and some extra work, when it seems like something that should "just work".

**Comment by JonRowe** [comment] 2019-05-21 16:21
Have you suggested a fix to the mongoid authors? Seems like this problem is best addressed over there. If an object responds to a field it should er... `respond_to?(field)` :joy:

**Comment by mltsy** [comment] 2019-05-28 00:10
I haven't... it's worth a shot.  I could see it making sense to scan all fields for a given model and generate the accessors when the model is loaded.

**Comment by myronmarston** [comment] 2019-05-28 02:21
> I could see it making sense to scan all fields for a given model and generate the accessors when the model is loaded.

I imagine the maintainers of mongoid might not be ok with scanning all fields ahead of time--such an approach could have a performance impact, and isn't needed.  The standard way to deal with this is to define `respond_to_missing?` to return `true` for the method names that `method_missing` handles.  In fact, as both of these blog posts indicate, defining `method_missing` without also defining `respond_to_missing?` is generally a bug:

https://thoughtbot.com/blog/always-define-respond-to-missing-when-overriding
https://makandracards.com/makandra/9821-when-overriding-method_missing-remember-to-override-respond_to_missing-as-well

It sounds like mongoid is buggy in that it dynamically responds to messages (via `method_missing`) without indicating as such using `respond_to_missing?`.  I'd encourage you to make a PR against mongoid addressing this.

**Comment by mltsy** [comment] 2019-05-28 14:24
Okay - two things, now that I've had a chance to test specific cases again:

1. That's not quite how it works currently - it actually doesn't respond to either `method_missing` or `respond_to_missing?`.  The first time you access or write a dynamic attribute using the dynamic attribute accessor method `[:field]` is when it defines an accessor for that attribute so that you can access it using `.field` in the future.
2. MongoID **does** actually scan the model upon loading and define those accessors to expose the fields as if they were normal fields, so the only broken case here is when the field is not set.  The error message it produces is an exception raised by have_attributes instead of the usual error message saying the value expected and the value it found.  In this case, the value it "found" doesn't exist, since the accessor method doesn't exist for dynamic attributes that haven't been set, but it might reasonably be represented as `nil`.  Or we might just say "this is the correct error you should get when you `expect(something).to have_attributes(that_dont: :exist)`"

I think ignoring this case would be reasonable, since the error message it produces makes sense (unless @agnel wants to argue otherwise?) but there is another case that is still a problem, namely:

```ruby
expect(model).not_to have_attributes(my_field: "something")
```

This should pass, but fails with an exception that model does not respond to `my_field` with 0 arguments

**Comment by JonRowe** [comment] 2019-05-28 15:22
> it actually doesn't respond to either method_missing or respond_to_missing?
>
> ```
> expect(model).not_to have_attributes(my_field: "something")
> ```
>
> This should pass, but fails with an exception that model does not respond to my_field with 0 arguments

I'm afraid it should fail, as Mongoid hasn't implemented the `respond_to?` check correctly. I suggest you raise that as a bug with them. Any dynamically defined "attributes" must either `respond_to?` or `respond_to_missing?` for this matcher to work.

**Comment by mltsy** [comment] 2019-05-28 15:47
Yeah, I mean there are certainly other valid ways for dynamic attributes to work (as in this case), but solving this compatibility problem seems like a job for an integration gem to me - maybe `mongoid-have-attributes` - something that either defines a new expectation (`have_dynamic_attributes`) or overwrites `have_attributes` such that it doesn't require models with dynamic attributes to `respond_to?` undefined fields.

**Comment by JonRowe** [comment] 2019-05-28 16:06
I believe there is a `mongoid-rspec` gem so you could certainly fix the behaviour there, but this is most certainly a bug in mongoid, it shouldn't have methods that don't implement respond to checks.

**Comment by mltsy** [comment] 2019-05-28 18:18
I think you may be misunderstanding how it works still?  If you have a Mongoid model that uses dynamic attributes, and try to access `.random_field` before it has been set on that model, it will raise a `NoMethodError` until you declare that dynamic field using `[:random_field]`, after which, it will respond to `.random_field` - which is consistent with the `respond_to?(:random_field)` result: `false` until you declare that field, after which it is `true`.  This design is (in my opinion) nicer than the alternative for dynamic attributes,, which is to never raise a NoMethodError, and simply return `nil` for any missing_method, assuming it's a dynamic attribute that hasn't been set yet.  This design preserves the NoMethodError for fields/methods that don't (yet) exist.

So it's not... inconsistent or a bug - it's just a design chhoice that's incompatible with the (reasonable) assumptions made by rspec-expectations, which are that you shouldn't be testing a model for an attribute with a name that the model doesn't even respond to.

**Comment by JonRowe** [comment] 2019-05-28 18:29
Oh ok, your explanation first time around made it sound like:

```
mongoid_model[:field] = :value
mongoid_model.respond_to?(:field) # false
expect(mongoid_model).to have_attributes(field: :value) # fails
```

If it's a case of:

```
mongoid_model[:field] = :value
mongoid_model.respond_to?(:field) # true
expect(mongoid_model).to have_attributes(field: :value) # fails
```

Then it's a bug with `have_attributes`, if an object properly returns from `respond_to?` then we can match on it, it's just that the error will be slightly confusing.

**Comment by mltsy** [comment] 2019-05-28 18:53
Ah cool - sorry for lack of clarity!

And actually, the latter is closer, but it actually works fine in the positive case (I'm not sure what @agnel was actually expecting to be different in the OP, other than perhaps the error message, which I think is fine as I was [trying to point out this morning](https://github.com/rspec/rspec-expectations/issues/1043#issuecomment-496539247)).  So these both work fine (AFAIC):

```ruby
mongoid_model[:field] = :value
mongoid_model.respond_to?(:field) # true
expect(mongoid_model).to have_attributes(field: :value) # passes!

mongoid_model[:field] = :value
mongoid_model.respond_to?(:other_field) # false
expect(mongoid_model).to have_attributes(other_field: :value) # fails
```
The latter fails with an error indicating model doesn't respond to `:other_field`, which is unusual, but that's because it's an unusual case, and it's technically correct.

This fails, somewhat unexpectedly:

```ruby
mongoid_model[:field] = :value
mongoid_model.respond_to?(:other_field) # false
expect(mongoid_model).not_to have_attributes(other_field: :value) # fails
```

This is the issue that one could argue should be resolved in an integration gem, but could potentially be resolved here as well using an extra option or some syntax to indicate a change in behavior on the negative assertion to accommodate this kind of dynamic attribute that doesn't exist until it's declared.

**Comment by JonRowe** [comment] 2019-05-28 19:35
Ok thanks for the clarification! For now I'm gong to close this as the matcher is working as designed and intended. `mongoid-rspec` could take this further.

**Closed by JonRowe** 2019-05-28 19:35 UTC
