### ISSUE TITLE
`include` matcher is not diffable enough

### ISSUE THREAD

**Issue by ojab** [rspec/rspec-expectations#1321] opened 2021-09-09 17:45 UTC
### Subject of the issue
Consider:
```ruby
RSpec.describe 'foo' do
  RSpec::Matchers.define :my_include do |expected|
    match do |actual|
      @expected_as_array = [[expected]]
      expect(actual).to include(expected)
    end

    diffable
  end

  let(:expected) { {a: 'a' * 100, b: 2} }
  let(:actual) { [{a: 'a' * 100  , b: 3}] }

  it { expect(actual).to include(expected) }
  it { expect(actual).to my_include(expected) }
end
```
![image](https://user-images.githubusercontent.com/153388/132735345-b48e04e3-97f8-439b-bedc-c825cf2401ad.png)

diff for `my_includes` shows exact lines where the issue occurred, because `include` matcher tries to compare single object with the whole array.
It's especially useful when working with real/more complicated data structures, for me it's unfortunately `spend 3 minutes reading output or try to diff by hand` usually on similar failures.

### Your environment
* Ruby version: 3.0.2 
* rspec-expectations version: current ~~master~~main

**Comment by pirj** [comment] 2021-09-10 00:01
A PR is welcome. You can start with a pending spec.
If you're up to improve this, check https://github.com/rspec/rspec-support/issues/365 (and listed issues) and https://github.com/rspec/rspec-support/pull/516 for details.

**Comment by ojab** [comment] 2021-09-10 00:28
I don't quite understand the expected solution here, while the single `expected` hash is quite easy, for multiple hashes we probably should find the closest objects in the `actual` enumerable and show diffs for them, but I guess it will lead to https://github.com/rspec/rspec-expectations/issues/1161.

And even if we knew what should be done, not sure if I'd have the capacity to do it.
So only `see something say something` issue for now and workaround in a private matcher :sweat_smile:

**Comment by JonRowe** [comment] 2021-10-01 10:27
Our current differ is limited in that it has to diff everything as strings, so it "prints" objects to strings then diffs those strings. As the include matcher is diffing an array vs a single element, it's always going to be "wrong" when it comes to the diff, and we don't currently have an api to provide the differ with a more intelligent solution.

Mutating the expected is a work around, but it might cause problems for re-use (which we support) and other downstream complications, for now I'm going to close this as a "can't fix" as its essentially a duplicate of out "we'd like to improve the differ" issues.

**Closed by JonRowe** 2021-10-01 10:27 UTC

**Comment by JonRowe** [comment] 2023-10-03 20:38
Theres a couple over on rspec/rspec-support, contributions for improving the differ or making it configurable with say `super_diff` would be welcome
