### ISSUE TITLE
Argument matches weirdness around time with activesupport

### ISSUE THREAD

**Issue by rwz** [rspec/rspec-expectations#958] opened 2016-12-15 18:13 UTC
Using rspec-expectations 3.5.0 on ruby 2.3.3

```ruby
it "should fail" do
  my_double = double
  expect(my_double).to receive(:call).with(time: Time.utc(2016, 8, 8, 0, 0, 24))
  my_double.call time: "2016-08-08T00:00:24Z"
end
```

This fails as expected when used without activesupport. If you `require "activesupport/all"` (I tried versions 4.2 and 5.0), the spec begins to pass though.

I couldn't find any documentation on how to make method expectation perform exact match and had to come up with the following workaround:

```ruby
RSpec::Matchers.define :exactly do |expected|
  match { |actual| actual == expected }
end

expect(my_double).to receive(:call).with(exactly(time: Time.utc(2016, 8, 8, 0, 0, 24)))
```

I believe this behavior can produce dangerous bugs and undermine developers confidence in their test setups. I also think that exact match should be an option or if it already is, it should be better discoverable in documentation.

**Comment by myronmarston** [comment] 2016-12-15 18:23
`Time.utc` (in your expectation) returns a `Time` object, but your call is passing a string.  I would not expect your expectation to pass, but it appears that activesupport does some monkeying with `Time#==` or `Time#===` (RSpec tries both internally when matching) to have them return `true` when the string version of a time is provided.  That seems like strange behavior in activesupport, TBH.

**Comment by rwz** [comment] 2016-12-15 18:34
Right, I fully realize that this is a direct result of activesupport's "freedom patching" (tm).

I'm saying that there should probably be an option to have exact arguments match that behaves similarly to the workaround I came up with. It could maybe have a different method like this:

```ruby
expect(thing).to receive(:foo).with_exactly(*args)
```

Also, Rspec is very popular in Rails community and this behavior seems like a bug that should be addressed spmehow in the long run.

**Comment by myronmarston** [comment] 2016-12-15 19:01
You can already do this:

``` ruby
expect(thing).to receive(:foo).with(an_object_eq_to(other_thing))
```

`an_object_eq_to` is an alias of `eq` that does only `==` matching.

What I don't understand is how this fixes your problem: if activesupport has redefined `==` when loaded, why does it improve things for you to use a matcher like this that avoids the `===` check that it normally does?

**Comment by rwz** [comment] 2016-12-15 19:07
I'm not sure what exactly activesupport does to cause this kind if behavior:

```
irb(main):001:0> require "active_support/all"
=> true
irb(main):002:0> time = Time.now
=> 2016-12-15 11:03:05 -0800
irb(main):003:0> time == time.iso8601
=> false
irb(main):004:0> time === time.iso8601
=> false
irb(main):005:0> time.iso8601 === time
=> false
irb(main):006:0> time.iso8601 == time
=> false
```

**Comment by myronmarston** [comment] 2016-12-15 19:09
Can you provide a repo with a reproducible example?

**Comment by rwz** [comment] 2016-12-15 19:10
Sure, gimme a minute

**Comment by rwz** [comment] 2016-12-15 19:24
https://github.com/rwz/rspec-as-time-example

**Comment by myronmarston** [comment] 2016-12-15 20:19
OK, I understand what's going on now.  I traced through activesupport to get the minimal set of monkey patches that trigger this behavior.  Here it is:

``` ruby
require 'date'

class DateTime
  # Layers additional behavior on DateTime#<=> so that Time and
  # ActiveSupport::TimeWithZone instances can be compared with a DateTime.
  def <=>(other)
    if other.kind_of?(Infinity)
      super
    elsif other.respond_to? :to_datetime
      super other.to_datetime rescue nil
    else
      nil
    end
  end
end

class String
  BLANK_RE = /\A[[:space:]]*\z/

  # A string is blank if it's empty or contains whitespaces only:
  #
  #   ''.blank?       # => true
  #   '   '.blank?    # => true
  #   "\t\n\r".blank? # => true
  #   ' blah '.blank? # => false
  #
  # Unicode whitespace is supported:
  #
  #   "\u00a0".blank? # => true
  #
  # @return [true, false]
  def blank?
    BLANK_RE === self
  end
end

class Time
  # Layers additional behavior on Time#<=> so that DateTime and ActiveSupport::TimeWithZone instances
  # can be chronologically compared with a Time
  def compare_with_coercion(other)
    # we're avoiding Time#to_datetime cause it's expensive
    if other.is_a?(Time)
      compare_without_coercion(other.to_time)
    else
      to_datetime <=> other
    end
  end
  alias_method :compare_without_coercion, :<=>
  alias_method :<=>, :compare_with_coercion
end

class String
  # Converts a string to a DateTime value.
  #
  #   "1-1-2012".to_datetime            # => Sun, 01 Jan 2012 00:00:00 +0000
  #   "01/01/2012 23:59:59".to_datetime # => Sun, 01 Jan 2012 23:59:59 +0000
  #   "2012-12-13 12:50".to_datetime    # => Thu, 13 Dec 2012 12:50:00 +0000
  #   "12/13/2012".to_datetime          # => ArgumentError: invalid date
  def to_datetime
    ::DateTime.parse(self, false) unless blank?
  end
end
```

That comes from 3 different activesupport files.  With it in place, it makes `Time#<=>` coerce non-time objets to date-time objects via `to_datetime`.  Comparable defines `==` in terms of `<=>` so it gets involved.  String has a `to_datetime` patch that allows it to be coerced.  `DateTime` likewise coerces the time to a datetime.  As a result, Rails has decided that a time object and a string representation of it should be considered equal, _as long as you call `==` on the time_ (it won't work the other way around).

This seems like crazy pants.  Strings and times aren't the same, but rails, in the name of convenience, has decided they should be, but only if you do the comparison with activesupport loaded, and only if you do the comparison a certain way.

Your IRB example does not demonstrate the issue because of your use of `Time.now`; the current time includes milliseconds, but those are lost when it roundtrips via `iso8601` and the comparison fails.  But if you construct the time using `Time.utc` you'll see the same behavior as in your spec.

Honestly, I don't think we should do anything about this.  We've documented our matchers to say what protocols they rely on.  Each object gets to decide what equality means for it.  If an object decides to implement `==` a certain way, as Rails has decide for time objects, we have to respect that.  It would be confusing for our matching logic to return `false` when a user can see `time == string_time` return true.

**Comment by myronmarston** [comment] 2016-12-15 20:23
BTW, the reason using `an_object_eq_to(time)` fixes the problem is because of how `eq` is defined: it uses `actual == expected` which results in `string_time == time`:

https://github.com/rspec/rspec-expectations/blob/f6a03426a39b2555c8ad67818b6ac99a69ec25c3/lib/rspec/matchers/built_in/eq.rb#L34-L36

I'd say that's an implementation detail, though; `==` is a protocol that RSpec expects to be symmetric (e.g. the truthiness of `a == b` should be the same as `b == a` for all a's and b's).  The fact that Rails implements a non-symmetric version of `==` is fundamentally broken, IMO.

**Comment by JonRowe** [comment] 2016-12-15 21:48
I don't think theres anything sane we can do about this

**Comment by rwz** [comment] 2016-12-15 21:59
I've complained to Rails, but I don't actually expect them to do anything about it without making backwards incompatible changes.

This is really sad. 😢

**Comment by myronmarston** [comment] 2016-12-15 22:01
Thanks for reporting upstream.

Agreed it's frustrating.

Closing.

**Closed by myronmarston** 2016-12-15 22:01 UTC
