### ISSUE TITLE
`eq` matcher produces confusing Diff message for a trailing new line

### ISSUE THREAD

**Issue by aeroastro** [rspec/rspec-expectations#1408] opened 2023-03-03 06:07 UTC
RSpec's built-in `eq` matcher is very useful for comparing two strings.
The Diff message for failing test allows developers to quickly find bugs especially for large size text.

However, I have found a confusing message when the diff is a trailing new line.

It says:

```
<The diff is empty, are your objects producing identical `#inspect` output?>
```

Here are the related issues.

* https://github.com/rspec/rspec-support/issues/70
* https://github.com/rspec/rspec-expectations/issues/570

### Your environment

* Ruby version: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin19]
* rspec-expectations version: rspec-expectations (3.12.2)

### Steps to reproduce

Following is the test code to reproduce this.

```ruby
require 'rspec'

def lines_to_text(*args)
  args.join("\n")
end

RSpec.describe '#lines_to_text' do
  subject { lines_to_text('foo', 'bar', 'baz') }

  context 'when there is diff inside string' do
    it 'shows diff elegantly' do
      expect(subject).to eq "foo\n\nbar\nbaz"
    end
  end


  context 'when there is a diff after the string' do
    it 'shows somewhat confusing message' do
      expect(subject).to eq <<~EXPECTED
        foo
        bar
        baz
      EXPECTED
    end
  end
end
```

### Expected behavior

For the second test:

```
  2) #lines_to_text when there is a diff after the string shows somewhat confusing message
     Failure/Error:
       expect(subject).to eq <<~EXPECTED
         foo
         bar
         baz
       EXPECTED

       expected: "foo\nbar\nbaz\n"
            got: "foo\nbar\nbaz"

       (compared using ==)

       Diff:
       @@ -1,3 +1,4 @@
        foo
        bar
        baz
       +

     # ./spec/sample_spec.rb:19:in `block (3 levels) in <top (required)>'
```

### Actual behavior

For the second test:

```
  2) #lines_to_text when there is a diff after the string shows somewhat confusing message
     Failure/Error:
       expect(subject).to eq <<~EXPECTED
         foo
         bar
         baz
       EXPECTED

       expected: "foo\nbar\nbaz\n"
            got: "foo\nbar\nbaz"

       (compared using ==)

       Diff:
         <The diff is empty, are your objects producing identical `#inspect` output?>
     # ./spec/sample_spec.rb:19:in `block (3 levels) in <top (required)>'
```

**Comment by JonRowe** [comment] 2023-03-03 08:38
Thanks, this is a duplicate of #570 as you linked to, as the trailing new line produces no diff you get this output.

**Closed** 2023-03-03 08:38 UTC
